services:
  # MQTT Broker
  mosquitto:
    networks:
      default:
        aliases:
          - mosquitto.dev
    image: docker.genee.cn/eclipse-mosquitto:2
    restart: always
    ports:
      - 1883:1883/tcp
      - 8083:8083/tcp
    volumes:
      - ../common/tmp:/tmp
      - ../common/localtime:/etc/localtime:ro
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  influxdb:
    networks:
      default:
        aliases:
          - influxdb.dev
    image: docker.genee.cn/influxdb:1.11
    restart: always
    ports:
      - 8086:8086/tcp
    volumes:
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime:ro
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb:/var/lib/influxdb
    command: 
      - influxd
      - -config
      - /etc/influxdb/influxdb.conf

networks:
  default:
    external: true
    name: dev

volumes:
  influxdb:
    external: true
