# Android
export ANDROID_SDK_ROOT="/opt/homebrew/share/android-commandlinetools"
export ANDROID_HOME="/opt/homebrew/share/android-commandlinetools"
# alias adb="$ANDROID_SDK_ROOT/platform-tools/adb"
# alias adbrr="adb shell input text rr"
# alias adbd="adb shell input keyevent 82"

export JAVA_HOME="/opt/homebrew/opt/openjdk@17"
export PATH="$JAVA_HOME/bin:$PATH"
