# Android
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
export ANDROID_HOME="$HOME/Library/Android/sdk"
alias adb="$ANDROID_SDK_ROOT/platform-tools/adb"
alias adbrr="adb shell input text rr"
alias adbd="adb shell input keyevent 82"

export JAVA_HOME="$HOME/Library/Java/JavaVirtualMachines/azul-16.0.2/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"
