services:
  mariadb:
    image: mariadb:10
    networks:
      default:
        aliases:
          - mariadb.dev
    ports:
      - 3306:3306/tcp
    volumes:
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 83719730
      MYSQL_USER: genee
      MYSQL_PASSWORD: 83719730
    restart: always
    privileged: true
    command: --port 3306
  redis:
    image: redis:alpine
    networks:
      default:
        aliases:
          - redis.dev
    ports:
      - 6379:6379/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/tmp
    restart: always
  beanstalkd:
    image: genee/beanstalkd
    networks:
      default:
        aliases:
          - beanstalkd.dev
    ports:
      - 11300:11300/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  default:
    name: dev
    external: true

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=host.docker.internal,hard,nolock,rw"
      device: ":/Volumes/Codes/container-volumes/mariadb"

