version: "3"

services:
  mariadb:
    image: mariadb:10.6
    hostname: mariadb.dev
    networks:
      default:
        aliases:
          - mariadb.dev
    ports:
      - 3306:3306/tcp
    volumes:
      - ../common/tmp:/tmp
      - ../common/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 83719730
      MYSQL_USER: genee
      MYSQL_PASSWORD: 83719730
    restart: always
  redis:
    image: redis:alpine
    hostname: redis.dev
    networks:
      default:
        aliases:
          - redis.dev
    ports:
      - 6379:6379/tcp
    volumes:
      - ../common/localtime:/etc/localtime:ro
      - ../common/tmp:/tmp
    restart: always

networks:
  default:
    name: dev

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=host.docker.internal,hard,nolock,rw"
      device: ":/Volumes/Codes/docker-volumes/mariadb"
