services:
  gini:
    image: genee/gini:php7.4-alpine
    networks:
      default:
        aliases:
          - gini.dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/tmp
      - ../.gitconfig:/root/.gitconfig
      - ../.git-credentials:/root/.git-credentials
      - ../.ssh:/root/.ssh
      - ./gini/profile.gini.sh:/etc/profile.d/zz_gini.sh:ro
      - ./gini/composer.config.json:/usr/local/share/composer/config.json
      - ./gini/start.d:/start.d
      - ./gini/composer-cache:/usr/local/share/composer/cache
      - ./gini/composer-vendor:/usr/local/share/composer/vendor
      - /Volumes/Codes/php:/data
    working_dir: /data/gini-modules
    restart: always

networks:
  default:
    name: dev
    external: true

