CODES="/Volumes/Codes"

function __php_run() {
    local work_dir=$(realpath --relative-to=$CODES/php $PWD)
    docker run --rm -it \
        --network name=dev \
        -v $CODES/php:/opt/php \
        -v $CODES/php/$work_dir/vendor:/data/$work_dir/vendor \
        -v $ENV_DIR/php/composer-cache:/usr/local/share/composer/cache \
        -v $ENV_DIR/php/composer-vendor:/usr/local/share/composer/vendor \
        -v $ENV_DIR/php/composer.config.json:/usr/local/share/composer/config.json \
        -v $ENV_DIR/php/gini/profile.gini.sh:/etc/profile.d/zz_gini.sh \
        -w /opt/php/$work_dir docker.genee.cn/php:8.3-alpine "$@"
}

alias gini="__php_run /opt/php/gini-modules/gini/bin/gini"
alias composer="__php_run composer"
alias php="__php_run php"
alias phpunit="__php_run vendor/bin/phpunit"
alias phpsh="__php_run bash"
