version: '3'

services:
  gini:
    image: genee/gini:php7.4-alpine
    hostname: gini
    networks:
      default:
        aliases:
          - gini.dev
    volumes:
      - ../common/localtime:/etc/localtime:ro
      - ../common/tmp:/tmp
      - ../.gitconfig:/root/.gitconfig
      - ../.git-credentials:/root/.git-credentials
      - ../.ssh:/root/.ssh
      - ./gini/profile.gini.sh:/etc/profile.d/zz_gini.sh:ro
      - ./gini/composer.config.json:/usr/local/share/composer/config.json
      - ./gini/start.d:/start.d
      - ./gini/composer-cache:/usr/local/share/composer/cache
      - ./gini/composer-vendor:/usr/local/share/composer/vendor
      - php:/data
    working_dir: /data/gini-modules
    restart: always

networks:
  dev:
    name: dev

volumes:
  php:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=host.docker.internal,hard,nolock,rw"
      device: ":/Volumes/Codes/php"

